runtime: go115 # golang version

env_variables:
  CLOUDSQL_CONNECTION_NAME: "taskeeper-355213:us-central1:taskeeperdb"
  SQL_USERNAME: "taskeeperbot"
  SQL_PASSWORD: "PutYourPasswordHere"
  CLOUDSQL_DBNAME: "taskeeperdatabase"
  REDISHOST: "10.42.152.83"
  REDISPORT: "6379"

vpc_access_connector:
  name: "projects/taskeeper-355213/locations/us-central1/connectors/taskeeperconn"